### ISSUE TITLE
Label the data

### ISSUE THREAD

**Issue by Lvdongzjh** [zakaria76al/USC#1]
Hello author, Could you tell me how to label the file.wav file data? Or Could you give a label example? For data(X_train, y_train, X_val, y_val) should be a numpy array. What does the numpy array look like?Looking forward to your reply.

**Comment by zakaria76al** [comment]
Hello, the file.wav is only for testing data preparation, it doesn't have any label, the datasets used are available publicly (DeepShip, and ShipsEar). About the data, one sample is a numpy array of 6 consecutive frames with the shape of (6, 15360) for the end-to-end model, and (6, 40, 31) for the hybrid model, and the channel equal **1** for both.

**Comment by sosohungry** [comment]
sequence = features.create_raw_sequences(data, params=p1)  
the output is a list and you need turn it to numpy array for testing
