### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by shaobaot** [zakaria76al/USC#2]
Thanks for your project.I don't konw how to use the raw signals to make the dataset and preprocess it.Can you help me?

**Comment by zakaria76al** [comment]
You can use a Python library to read your dataset such as Librosa and then pass it through the training function in model.py.
You can also modify the training function by adding a data loader to avoid memory consumption.

**Comment by shaobaot** [comment]
Can i have your email? I am a student and I want to study your code.I have done this for long time but not success,  this project is important for me, thank you very much!
